### ISSUE TITLE
Most abundant genera across a complete phyloseq object 

### ISSUE THREAD

**Issue by slambrechts** [gmteunisse/fantaxtic#26]
Hi, 

I'm trying to use fantaxtic to get the top 10 most abundant genera across a complete phyloseq object and list the relative abundances of these top genera. I was trying to do this like so:

```
top <- top_taxa(physeq, 
                tax_level = "Genus", 
                n_taxa = 10)
```

But I get:

```
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Maybe this has something to do with the fact that I classified my OTUs using Lotus2, and therefore there are "?" in my tax table?

**Comment by gmteunisse** [comment]
Question marks should definitely be replaced with NA values. Another thing to check is that the tax_table has the correct order (col_1=kingdom, …, col_n=species). If that doesn’t solve it, could you post a reproducible example with data?
________________________________
From: Sam Lambrechts ***@***.***>
Sent: Tuesday, December 12, 2023 11:21:12 AM
To: gmteunisse/fantaxtic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gmteunisse/fantaxtic] Most abundant genera across a complete phyloseq object (Issue #26)


Hi,

I'm trying to use fantaxtic to get the top 10 most abundant genera across a complete phyloseq object and list the relative abundances of these top genera. I was trying to do this like so:

top <- top_taxa(physeq,
                tax_level = "Genus",
                n_taxa = 10)


But I get:

Error in dimnames(x) <- dn :
  length of 'dimnames' [1] not equal to array extent


Maybe this has something to do with the fact that I classified my OTUs using Lotus2, and therefore there are "?" in my tax table?

**Comment by slambrechts** [comment]
Thank you for the info

col_1 is listed as Domain instead of kingdom at the moment

I will first replace question marks with NA values

**Comment by gmteunisse** [comment]
Has your issue been resolved?

**Comment by slambrechts** [comment]
Hi, no the problem remained after the modifications, so I ended up using something else

**Comment by gmteunisse** [comment]
I'm sad to hear that. Could you post a reproducible example? It would be nice if I can see what the problem is and fix it.
