### ISSUE TITLE
Fail to install Fantaxtic

### ISSUE THREAD

**Issue by vfonti** [gmteunisse/Fantaxtic#3]
Hello! Fantaxtic seems to have some brilliant functions and I am keen to try it on my dataset.
Unfortunately, I cannot find the way to complete it's installation. I have tried both through `remotes `and `devtools `but nothing has worked. I've updated packages that needed it and re-installed `rlang`.
This is the error message I get:

```
> devtools::install_github("gmteunisse/Fantaxtic")
Downloading GitHub repo gmteunisse/Fantaxtic@HEAD
Skipping 1 packages not available: phyloseq
√  checking for file 'C:\Users\User\AppData\Local\Temp\RtmpoN2hMC\remotes31401b77e5\gmteunisse-Fantaxtic-4653973/DESCRIPTION' ...
-  preparing 'fantaxtic':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'fantaxtic_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/User/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'fantaxtic' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'fantaxtic'
* removing 'C:/Users/User/Documents/R/win-library/4.0/fantaxtic'
Error: Failed to install 'fantaxtic' from GitHub:
  (converted from warning) installation of package ‘C:/Users/User/AppData/Local/Temp/RtmpoN2hMC/file31405bba16c6/fantaxtic_0.1.0.tar.gz’ had non-zero exit status
```

I use a Windows machine and my R version is 4.0.1 .
Any suggestions?
V.

**Comment by gmteunisse** [comment]
Hi, thanks for wanting to try out this package! I haven't maintained this package in a while, my apologies for the late response. It seems that you don't have `phyloseq` installed. You can install it using Bioconductor:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("phyloseq")

```

Thanks for bringing this to my attention, I will make sure to add it to the install notes.

**Comment by gmteunisse** [comment]
On second though, you must have phyloseq installed. It seems that your issue arises from ggplot2 having been built under a different version, which results in a warning normally but is converted to an error. You might be able to resolve them by upgrading your R installation to the latest version. I found this issue https://github.com/r-lib/remotes/issues/403, which might help you in the right direction.

**Comment by vfonti** [comment]
Hello, 
Thank you very much for replying.
Yeah, I do have and work with phyloseq. And, actually, I am already using the latest R version (4.0.3). Maybe I can try reinstall ggplot2 and phyloseq?

Vivi

**Comment by gmteunisse** [comment]
Yes, do try. Also try using the `remotes` package from the issue I linked
previously to install `Fantaxtic` - they seem to have a workaround. Wish I
could help you any better!
