### ISSUE TITLE
grouped samples in the X-axis

### ISSUE THREAD

**Issue by mariemh23** [gmteunisse/Fantaxtic#4]
Hi!!

Fantaxtic package is .... fantastic.
I was wondering if it was possible to display the bars according to the sample group in the x-axis (e.g. sick, healthy) instead of the sample names.
Thanks

**Comment by gmteunisse** [comment]
Glad to hear it's useful to you! I'll see if I can add that feature for you in an update, it shouldn't be too much work.

**Comment by antoine4ucsd** [comment]
hello. I am also very interested in this new feature. this package is really cool. do you have any udpates?
thank you

**Comment by gmteunisse** [comment]
Hi Antoine, thanks for the complement. I haven't been maintaining this package, so this feature has not been implemented explicitly. However, you can achieve something close to what you want using the `facet_by = 'grouping_factor'` argument. This will add a ggplot2 facet to the plot, allowing you to group by one (using `facet_by`) or two (using `grid_by`) grouping factors. I hope that this is useful for you.

**Comment by antoine4ucsd** [comment]
I already used this facet (great) but trying to do smthg like below where you have one column per sample but the samples are grouped by CST class. the facet is used in my case to group by cohort...
<img width="249" alt="Screen Shot 2022-04-04 at 9 21 33 AM" src="https://user-images.githubusercontent.com/18502631/161493385-582fb4b6-8b23-4705-8584-ecc6605c8e73.png">
.

**Comment by gmteunisse** [comment]
I understand. Adding a second facet (e.g. "group_a + group_b") or gridding (`facet_by` + `grid_by`) are the only options that are implemented at the moment. I haven't got time to implement the feature, but if you do, feel free to make a pull request and I will happily integrate your code.

**Comment by antoine4ucsd** [comment]
thank you

**Comment by gmteunisse** [comment]
This won't be implemented, it turns out to be quite difficult. However, when `sample_order` is specified, samples are placed into a specific order. You could manually implement a solution to then draw the lines and add the annotations.
