### ISSUE TITLE
Extract data that went into the bar plot

### ISSUE THREAD

**Issue by pauGuas** [gmteunisse/Fantaxtic#6]
Hi, I need a table showing the relative abundance of each taxon in each sample.  Is there a way to extract that data from the fantaxtic bar plot?

I also want to double check.... "Other" just means taxa that weren't in the top most abundant, right? And not that it's just a taxon that isn't identified?

Thank you!

**Comment by gmteunisse** [comment]
Hi pauGaus,

Thanks for using fantaxtic. 

The `get_top_taxa` function outputs a phyloseq object with that information if  `relative = T`. This does have the non-top taxa collapsed into "Other". To access this table, run the following:

```
# Get the top 10 taxa and collapse all otehr into "Other". Make abundances relative.
ps_tmp <- get_top_taxa(physeq_obj = physeq_obj, n = 10, relative = TRUE,
                       discard_other = FALSE, other_label = "Other")
rel_abun <- phyloseq::otu_table(ps_tmp)

# The taxon names are stored in the tax table
tax_names <- tax_table(ps_tmp)

# Bind the two together
final_table <- cbind(tax_names, rel_abun)
```

If you don't want to collapse the taxa into "Other" and want information for all taxa instead, you'll need to calculate relative abundances yourself. Use the following code in base R:

```
#Get the tax and OTU tables
otu_tbl <- as.data.frame(phyloseq::otu_table(physeq_obj))

#Check the orientation of the otu_tbl and change if required
if (!taxa_are_rows(phyloseq::otu_table(physeq_obj))){
  otu_tbl <- as.data.frame(t(otu_tbl))
}

#Transform absolute taxon counts to relative values
otu_tbl <- apply(otu_tbl, 2, function(x){
      x / sum (x)
})

# The taxon names are stored in the tax table
tax_names <- tax_table(physeq_obj)

# Bind the two together
final_table <- cbind(tax_names, rel_abun)
```

You are correct that "Other" just means all the taxa that weren't in the top most abundant.

Hope this helps you.

**Comment by pauGuas** [comment]
@gmteunisse  thank you so much for your answer! I am running into an error "Error in cbind2(argl[[i]], r) : 
  number of rows of matrices must match (see arg 2)"

**Comment by gmteunisse** [comment]
No worries @pauGuas. It's an error in the cbind command, which is telling you that the otu_tbl and the tax_tbl have a different number of rows. Check whether the number of rows are what you expect (`nrow(rel_abun); nrow(otu_tbl); nrow(tax_names)`).

Which of the two solutions are you using? I see that I made an error in the second code block, the last line should be `final_table <- cbind(tax_names, otu_tbl)`.

**Comment by pauGuas** [comment]
@gmteunisse  I am getting 11 for tax_names and 17 for rel_abun (rel_abun is the correct one for the code I'm using :))

**Comment by gmteunisse** [comment]
Thanks pauGaus. It's 11, because they are the top 10 + `"Other"`. It sounds like the `rel_abun` table needs to be transposed. Try `final_table <- cbind(tax_name, t(rel_abun))`. Let me know if that works!

**Comment by gmteunisse** [comment]
Glad it worked! Good luck with your research.

**Comment by pauGuas** [comment]
Sorry, one more question.  In the table, there is a point where the proportion suddenly becomes whole numbers.  See screenshot:

![image](https://user-images.githubusercontent.com/84878533/151240391-6675e609-e376-416b-9c4b-0059622b0616.png)

**Comment by gmteunisse** [comment]
Did you cbind multiple times by any chance? I think the table should only be 7 taxonomic ranks + 17 samples = 24 columns, which means that from column X on, samples may be repeated.
________________________________

**Comment by pauGuas** [comment]
I tried again from the start and still the same issue.

**Comment by gmteunisse** [comment]
That's no good. I had another look at the output from get_top_taxa, and it indeed does not return proportions - it only selects by relative abundance, but returns counts. My bad!

The code chunk below should give you the correct table, or at least, it does for me with the GlobalPatterns data. Swap in your own data and it should be good.

```
require("fantaxtic")

# Load test data
data(GlobalPatterns)

# Get the top taxa and extract the otu_tbl
ps_tmp <- get_top_taxa(physeq_obj = GlobalPatterns, n = 10, relative = TRUE,
                       discard_other = FALSE, other_label = "Other")
otu_tbl <- phyloseq::otu_table(ps_tmp)

#Check the orientation of the otu_tbl and transpose if required
if (!taxa_are_rows(phyloseq::otu_table(physeq_obj))){
  otu_tbl <- as.data.frame(t(otu_tbl))
}

# Calculate relative abundances
rel_abun <- apply(otu_tbl, 2, function(x){
  x / sum (x)
})

# Sanity check: all columns sum to 1?
apply(rel_abun, 2, sum)

# Extract taxon names
tax_names <- tax_table(ps_tmp)

# Combine
final_table <- cbind(tax_names, rel_abun)
```
